# Generated by Django 4.2 on 2023-05-20 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('size', models.FloatField(default=0)),
                ('hash', models.CharField(max_length=300)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='app.file')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folder', related_query_name='folder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
