# Generated by Django 4.2 on 2023-05-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
    ]
