# Generated by Django 4.2 on 2023-05-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='files',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='app.file'),
        ),
    ]
