# Generated by Django 4.2 on 2023-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_folder_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='files',
        ),
        migrations.AddField(
            model_name='folder',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='folder', to='app.file'),
        ),
    ]
