# Generated by Django 4.2 on 2023-05-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_file_user_delete_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='last_modified',
        ),
    ]
